//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace funplay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string GameNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public string Developer { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public string MainImg { get; set; }
        public string SubImg { get; set; }
    }
}
