//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace funplay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int Id { get; set; }
        public bool IsValid { get; set; }
        public string UserNo { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string Mp3 { get; set; }
        public string Picture { get; set; }
        public int PriceMax { get; set; }
        public Nullable<int> PriceMedium { get; set; }
        public Nullable<int> PriceMin { get; set; }
        public int MainTypeNo { get; set; }
        public string SecodaryTypeNo { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Upload { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
    }
}
